In [1]:
#Bibliotecas
import pandas as pd
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive

In [2]:
#Carregar dados
df = pd.read_csv("/content/drive/MyDrive/Colab Notebooks/DB/TCC/tweets_escot_dbv_2023-05-05_2021-01-01.csv", engine='python')

In [3]:
df

,Unnamed: 0,Date,User,Tweet,ID
0,0,2023-05-04 23:56:16+00:00,calotey,é absurdo como eu sou apaixonada pelo escotismo,1.654274e+18
1,1,2023-05-04 23:41:15+00:00,Charloutt_,"Campori Osório 2022, um dos momentos da minha ...",1.654270e+18
2,2,2023-05-04 23:40:07+00:00,sorenzitos,"@ToinPierre Desbravador preservação, pela, bai...",1.654270e+18
3,3,2023-05-04 22:55:38+00:00,lovers_ranpo,@alyss0nz @i4geto É uma quantidade absurda e d...,1.654259e+18
4,4,2023-05-04 22:40:02+00:00,_Wallkiri_,"@TalesMendes15 Lado bom esse mesmo, março e o ...",1.654255e+18
...,...,...,...,...,...
13327,13325,2022-11-26 13:23:42+00:00,patriciacoelho_,I'm at Grupo Escoteiro Säo Mário - 144 in Pira...,1.596495e+18
13328,13326,2022-11-26 13:18:22+00:00,FJarwoski,"A MARCHA DOS ESCOTEIROS (FINAL): ""OS MILIONARI...",1.596494e+18
13329,13327,2022-11-26 13:14:16+00:00,SHESA_MYTH,hj eu tenho escoteiro a tarde e apresentação d...,1.596493e+18
13330,13328,2022-11-26 13:06:45+00:00,Anaclar188,Esse campori tá sendo uma mistura de sentiment...,1.596491e+18
13331,13329,2022-11-26 12:55:00+00:00,rafamore1ra,Que histeria coletiva da #FlaTT no caso Doriva...,1.596488e+18

In [6]:
from random import randrange, uniform
print(randrange(0, 13332)) #faixa de inteiro

9178

In [7]:
dff = pd.DataFrame(columns=['Date', 'User', 'Tweet', 'ID'])
dff

Empty DataFrame
Columns: [Date, User, Tweet, ID]
Index: []

In [8]:
dff.append(df.iloc[1], ignore_index=True)

<ipython-input-8-238efca6dfc9>:1: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dff.append(df.iloc[1], ignore_index=True)

,Date,User,Tweet,ID,Unnamed: 0
0,2023-05-04 23:41:15+00:00,Charloutt_,"Campori Osório 2022, um dos momentos da minha ...",1.654270e+18,1

In [19]:
df.iloc[1]
nova_linha = pd.DataFrame.from_records({'Date': df.iloc[1]['Date'], 'User': df.iloc[1]['User'], 'Tweet': df.iloc[1]['Tweet'], 'ID': df.iloc[1]['ID']}, index=[0])
dff = pd.concat([dff, nova_linha])
#dff.concat(nova_linha)
dff

,Date,User,Tweet,ID
0,2023-05-04 23:41:15+00:00,Charloutt_,"Campori Osório 2022, um dos momentos da minha ...",1.654270e+18
0,2023-05-04 23:41:15+00:00,Charloutt_,"Campori Osório 2022, um dos momentos da minha ...",1.654270e+18

In [ ]:
#dff = pd.DataFrame()
count = 0
while count < 101:
  valor = randrange(0, 13332)
  dff.append(df.iloc[count], ignore_index=True)
  count = count + 1

<ipython-input-44-848a9ef96af8>:5: FutureWarning: The frame.append method is deprecated and will be removed from pandas in a future version. Use pandas.concat instead.
  dff.append(df.iloc[count], ignore_index=True)

In [ ]:
#dff = df
#dff

#for i in range(13):
# print(dff.iloc[i])
dff

Empty DataFrame
Columns: []
Index: []